import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { CsvAdviceResponse, CsvAdviceBullet } from '../types/csvAdvice'

export function generateCsvAdvicePdf(advice: CsvAdviceResponse, dateRange: string): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // Title
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Stocky Analyse — CSV Trader Advice', pageWidth / 2, y, { align: 'center' })
  y += 8

  // Date range
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(`Analysis Period: ${dateRange}`, pageWidth / 2, y, { align: 'center' })
  y += 6

  // Overall Score
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(`Overall Grade: ${advice.overall_score}`, pageWidth / 2, y, { align: 'center' })
  y += 4

  // Divider
  doc.setDrawColor(200, 200, 200)
  doc.line(14, y, pageWidth - 14, y)
  y += 8

  // Executive Summary
  if (advice.summary) {
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text('Executive Summary', 14, y)
    y += 7
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(40, 40, 40)
    const summaryLines = doc.splitTextToSize(advice.summary, pageWidth - 28)
    doc.text(summaryLines, 14, y)
    y += summaryLines.length * 5 + 8
  }

  // Key Metrics Table
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('Key Metrics', 14, y)
  y += 2

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Win Rate', `${advice.metrics.win_rate}%`],
      ['Payoff Ratio', `${advice.metrics.rr_ratio}:1`],
      ['Profit Factor', `${advice.metrics.profit_factor}`],
      ['Sharpe Ratio', `${advice.metrics.sharpe_ratio}`],
      ['Kelly Criterion', `${advice.kelly_pct}% (Half: ${advice.half_kelly_pct}%)`],
      ['Total P&L', `Rs ${advice.metrics.total_pnl.toLocaleString('en-IN')}`],
      ['Max Drawdown', `${advice.metrics.max_drawdown_pct}%`],
      ['Expectancy', `Rs ${advice.metrics.expectancy.toLocaleString('en-IN')}/trade`],
      ['Recovery Factor', `${advice.metrics.recovery_factor}`],
      ['Monthly Consistency', `${advice.metrics.monthly_consistency}%`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [201, 169, 110], textColor: 17, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
  })

  y = (doc as ReturnType<typeof autoTable> & { lastAutoTable: { finalY: number } } & jsPDF).lastAutoTable?.finalY
    ?? (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY
    ?? y + 80
  y += 10

  // Analysis Sections
  for (const section of advice.sections) {
    if (y > 240) { doc.addPage(); y = 20 }
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text(section.title, 14, y)
    y += 6

    // Data points
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(60, 60, 60)
    for (const dp of section.data_points) {
      if (y > 275) { doc.addPage(); y = 20 }
      doc.text(`${dp.label}: ${dp.value}`, 18, y)
      y += 4.5
    }
    y += 2

    // Insight
    doc.setFontSize(9)
    doc.setTextColor(40, 40, 40)
    const insightLines = doc.splitTextToSize(section.insight, pageWidth - 32)
    if (y + insightLines.length * 4.5 > 275) { doc.addPage(); y = 20 }
    doc.text(insightLines, 18, y)
    y += insightLines.length * 4.5 + 8
  }

  // Bullet sections
  const renderBullets = (title: string, bullets: CsvAdviceBullet[]) => {
    if (y > 255) { doc.addPage(); y = 20 }
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text(title, 14, y)
    y += 7
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(40, 40, 40)
    bullets.forEach((b, i) => {
      if (y > 275) { doc.addPage(); y = 20 }
      const text = `${i + 1}. ${b.text}`
      const lines = doc.splitTextToSize(text, pageWidth - 28)
      doc.text(lines, 14, y)
      y += lines.length * 4.5 + 3
    })
    y += 5
  }

  renderBullets('Strengths', advice.strengths)
  renderBullets('Weaknesses', advice.weaknesses)
  renderBullets('Recommendations', advice.recommendations)

  // Footer
  if (y > 275) { doc.addPage(); y = 20 }
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by Stocky Analyse — F&O P&L Analytics Dashboard', pageWidth / 2, 285, { align: 'center' })

  doc.save('stocky-analyse-csv-advice.pdf')
}
